project:
  type: website

execute:
  freeze: auto

website:
  title: "RTromsø - R @ UiT"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: Events
      - resources.qmd
      - href: tutorials.qmd
        text: Tutorials



  sidebar:
    - title: "Events"
      style: "docked"
      background: light
      contents:
        - events.qmd
        - 2024-06-18.qmd
        - 2024-06-14.qmd
        - 2024-04-17.qmd


format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    grid:
      margin-width: 450px

editor: visual

